// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // firebase: {
  // apiKey: 'AIzaSyAvXVfw2lwZ9X_Ls7sCsGo2Bq6gflXq2QM',
  // authDomain: 'kukerja-indonesia.firebaseapp.com',
  // databaseURL: 'https://kukerja-indonesia.firebaseio.com',
  // projectId: 'kukerja-indonesia',
  // storageBucket: 'kukerja-indonesia.appspot.com',
  // messagingSenderId: '339885625717',
  // appId: '1:339885625717:android:7781b0876b0c67d625833c',
  // },


  // static const FirebaseOptions web = FirebaseOptions(
  //   apiKey: 'AIzaSyDyBOcy1DbmLIf_nkquzRi0pYneu-2E4bQ',
  //   appId: '1:532468117983:web:7a8b7a9ca01c7b1ac8946a',
  //   messagingSenderId: '532468117983',
  //   projectId: 'landing-page-3dcac',
  //   authDomain: 'landing-page-3dcac.firebaseapp.com',
  //   storageBucket: 'landing-page-3dcac.appspot.com',
  // );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvXVfw2lwZ9X_Ls7sCsGo2Bq6gflXq2QM',
    authDomain: 'kukerja-indonesia.firebaseapp.com',
    databaseURL: 'https://kukerja-indonesia.firebaseio.com',
    projectId: 'kukerja-indonesia',
    storageBucket: 'kukerja-indonesia.appspot.com',
    messagingSenderId: '339885625717',
    appId: '1:339885625717:android:7781b0876b0c67d625833c',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSNBc5TsVa4aA6c0OJdn4o3kxT-tlZyTE',
    appId: '1:532468117983:android:80e0473963eca3dbc8946a',
    messagingSenderId: '532468117983',
    projectId: 'landing-page-3dcac',
    storageBucket: 'landing-page-3dcac.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAA5ze-YRejq-PtMKH2d9qStjv6dicns8g',
    appId: '1:532468117983:ios:e9507cd346b613e3c8946a',
    messagingSenderId: '532468117983',
    projectId: 'landing-page-3dcac',
    storageBucket: 'landing-page-3dcac.appspot.com',
    iosClientId: '532468117983-avg409a1prnu0f5rau00n9ne12ekkqoi.apps.googleusercontent.com',
    iosBundleId: 'com.example.cloningWeb',
  );
}
